include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: 
    - build/**
    - lib/swagger_generated_code/**
    - lib/**.g.dart
  errors:
    always_use_package_imports: error
    directives_ordering: error
    prefer_single_quotes: error
    require_trailing_commas: error
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    - always_use_package_imports
    - directives_ordering
    - prefer_single_quotes
    - require_trailing_commas
