// Mocks generated by Mockito 5.3.2 from annotations
// in gruene_app/test/screens/onboarding/onboarding_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:gruene_app/net/onboarding/data/subject.dart' as _i4;
import 'package:gruene_app/net/onboarding/data/topic.dart' as _i3;
import 'package:gruene_app/net/onboarding/repository/onboarding_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OnboardingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingRepository extends _i1.Mock
    implements _i2.OnboardingRepository {
  @override
  Set<_i3.Topic> listTopic() => (super.noSuchMethod(
        Invocation.method(
          #listTopic,
          [],
        ),
        returnValue: <_i3.Topic>{},
        returnValueForMissingStub: <_i3.Topic>{},
      ) as Set<_i3.Topic>);
  @override
  Set<_i4.Subject> listSubject() => (super.noSuchMethod(
        Invocation.method(
          #listSubject,
          [],
        ),
        returnValue: <_i4.Subject>{},
        returnValueForMissingStub: <_i4.Subject>{},
      ) as Set<_i4.Subject>);
  @override
  bool onboardingSend(
    List<_i3.Topic>? topics,
    List<_i4.Subject>? subjects,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #onboardingSend,
          [
            topics,
            subjects,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
