#!/bin/sh

# Install this pre-commit hook by running the following command in the project root:
# ln -s ../../.github/hooks/pre-commit .git/hooks/pre-commit

# Regenerate circleci config.yml if necessary
CIRCLECI_CONFIG_FILES=$(git diff --cached --name-only .circleci/src)

if [ ! -z "$CIRCLECI_CONFIG_FILES" ]; then
  # Abort if circleci command line tools are not installed
  if ! command -v circleci; then
    echo "You need to install circleci in order to commit and update the circleci config"
    exit 1
  fi

  echo "$CIRCLECI_CONFIG_FILES" | ./tools/circleci-update-config
  echo "$CIRCLECI_CONFIG_FILES" | xargs git add
  xargs git add .circleci/config.yml
fi

# Format Dart Files
DART_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.dart" | sed 's| |\\ |g')

if [ ! -z "$DART_FILES" ]; then
  if [ ! -x "$(command -v fvm)" ]; then
    echo "You need to install fvm in order to commit and format files"
    exit 1
  fi

  echo "$DART_FILES" | xargs fvm dart format -l 120
  echo "$DART_FILES" | xargs git add
fi
